-- Inserts some initial data
INSERT INTO "platform" (id, name, simple_name) VALUES
    (0, 'Windows', 'PC'),
    (1, 'Mac', 'OSX'),
    (2, 'Nintendo Entertainment System', 'NES'),
    (3, 'Sega Genesis', 'Genesis'),
    (4, 'Playstation 1', 'PS1'),
    (5, 'Nintendo 64', 'N64');

-- Inserts N64 games
INSERT INTO "game" (name, platform_id) VALUES
    ('1080° Snowboarding', 5),
    ('64 Hanafuda: Tenshi no Yakusoku', 5),
    ('64 Ozumo', 5),
    ('64 Ozumo 2', 5),
    ('64 Trump Collection: Alice no Waku Waku Trump World', 5),
    ('Aero Fighters Assault', 5),
    ('AeroGauge', 5),
    ('AI Shogi 3', 5),
    ('Aidyn Chronicles: The First Mage', 5),
    ('Air Boarder 64', 5),
    ('All-Star Baseball 99', 5),
    ('All-Star Baseball 2000', 5),
    ('All-Star Baseball 2001', 5),
    ('All Star Tennis ''99•Yannick Noah All Star Tennis ''99FRA', 5),
    ('Armorines: Project S.W.A.R.M.', 5),
    ('Army Men: Air Combat', 5),
    ('Army Men: Sarge''s Heroes', 5),
    ('Army Men: Sarge''s Heroes 2', 5),
    ('Asteroids Hyper 64', 5),
    ('Automobili Lamborghini', 5),
    ('Bakuretsu Muteki Bangai-O', 5),
    ('Bakusho Jinsei 64: Mezase! Resort O', 5),
    ('Banjo-Kazooie', 5),
    ('Banjo-Tooie', 5),
    ('Bass Hunter 64', 5),
    ('Bass Masters 2000', 5),
    ('Bass Rush: ECOGEAR PowerWorm Championship', 5),
    ('Batman Beyond: Return of the Joker•Batman of the Future: Return of the JokerPAL', 5),
    ('BattleTanx', 5),
    ('BattleTanx: Global Assault', 5),
    ('Battlezone: Rise of the Black Dogs', 5),
    ('Beetle Adventure Racing!•HSV Adventure RacingAUS', 5),
    ('Big Mountain 2000', 5),
    ('Bio F.R.E.A.K.S.', 5),
    ('Blast Corps', 5),
    ('Blues Brothers 2000', 5),
    ('Body Harvest', 5),
    ('Bomberman 64', 5),
    ('Bomberman 64', 5),
    ('Bomberman 64: The Second Attack', 5),
    ('Bomberman Hero', 5),
    ('Bottom of the 9th', 5),
    ('Brunswick Circuit Pro Bowling', 5),
    ('Buck Bumble', 5),
    ('A Bug''s Life', 5),
    ('Bust-A-Move ''99•Bust-A-Move 3 DXPAL', 5),
    ('Bust-A-Move 2: Arcade Edition', 5),
    ('California Speed', 5),
    ('Carmageddon 64', 5),
    ('Castlevania', 5),
    ('Castlevania: Legacy of Darkness', 5),
    ('Centre Court Tennis', 5),
    ('Chameleon Twist', 5),
    ('Chameleon Twist 2', 5),
    ('Charlie Blast''s Territory', 5),
    ('Chopper Attack', 5),
    ('Choro Q 64 2: Hachamecha Grand Prix Race', 5),
    ('Chokukan Night: Pro Yakyu King', 5),
    ('Chokukan Night: Pro Yakyu King 2', 5),
    ('ClayFighter 63⅓', 5),
    ('ClayFighter Sculptor''s Cut', 5),
    ('Command & Conquer', 5),
    ('Conker''s Bad Fur Day', 5),
    ('Cruis''n Exotica', 5),
    ('Cruis''n USA', 5),
    ('Cruis''n World', 5),
    ('Custom Robo', 5),
    ('Custom Robo V2', 5),
    ('CyberTiger', 5),
    ('Daikatana', 5),
    ('Dance Dance Revolution Disney Dancing Museum', 5),
    ('Dark Rift', 5),
    ('Densha de Go! 64', 5),
    ('Derby Stallion 64', 5),
    ('Destruction Derby 64', 5),
    ('Dezaemon 3D', 5),
    ('Diddy Kong Racing', 5),
    ('Donald Duck: Goin'' Quackers•Donald Duck''s Quack AttackPAL', 5),
    ('Disney''s Tarzan', 5),
    ('Donkey Kong 64', 5),
    ('Doom 64', 5),
    ('Doraemon: Nobita to Mittsu no Seireiseki', 5),
    ('Doraemon 2: Nobita to Hikari no Shinden', 5),
    ('Doraemon 3: Nobita no Machi SOS!', 5),
    ('Dobutsu no Mori', 5),
    ('Dr. Mario 64', 5),
    ('Dual Heroes', 5),
    ('Duck Dodgers Starring Daffy Duck•Daffy Duck starring as Duck DodgersPAL', 5),
    ('Duke Nukem 64', 5),
    ('Duke Nukem: Zero Hour', 5),
    ('Earthworm Jim 3D', 5),
    ('ECW Hardcore Revolution', 5),
    ('Eiko no Saint Andrews', 5),
    ('Elmo''s Letter Adventure', 5),
    ('Elmo''s Number Journey', 5),
    ('Excitebike 64', 5),
    ('Extreme-G', 5),
    ('Extreme-G 2', 5),
    ('F-1 World Grand Prix', 5),
    ('F-1 World Grand Prix II', 5),
    ('F-Zero X', 5),
    ('F1 Pole Position 64', 5),
    ('F1 Racing Championship', 5),
    ('Famista 64', 5),
    ('FIFA ''99', 5),
    ('FIFA: Road to World Cup 98', 5),
    ('FIFA Soccer 64•FIFA 64PAL', 5),
    ('Fighters Destiny', 5),
    ('Fighter Destiny 2', 5),
    ('Fighting Force 64', 5),
    ('Flying Dragon', 5),
    ('Forsaken 64•ForsakenPAL', 5),
    ('Fox Sports College Hoops ''99', 5),
    ('G.A.S.P!! Fighters'' NEXTream•Deadly ArtsNA', 5),
    ('Gauntlet Legends', 5),
    ('Getter Love!!', 5),
    ('Gex 3: Deep Cover Gecko', 5),
    ('Gex 64: Enter the Gecko', 5),
    ('Glover', 5),
    ('Goemon Mononoke Sugoroku', 5),
    ('Goemon''s Great Adventure•Mystical Ninja 2: Starring GoemonPAL', 5),
    ('Golden Nugget 64', 5),
    ('GoldenEye 007', 5),
    ('GT 64: Championship Edition', 5),
    ('Hamster Monogatari 64', 5),
    ('Harvest Moon 64', 5),
    ('Heiwa Pachinko World 64', 5),
    ('Hercules: The Legendary Journeys', 5),
    ('Hexen', 5),
    ('Hey You, Pikachu!', 5),
    ('Hot Wheels Turbo Racing', 5),
    ('Hybrid Heaven', 5),
    ('Hydro Thunder', 5),
    ('Ide Yosuke no Mahjong Juku', 5),
    ('Iggy''s Reckin'' Balls', 5),
    ('Indiana Jones and the Infernal Machine', 5),
    ('Indy Racing 2000', 5),
    ('International Superstar Soccer ''98', 5),
    ('International Superstar Soccer 2000', 5),
    ('International Superstar Soccer 64', 5),
    ('International Track & Field 2000•International Track & Field: Summer GamesPAL', 5),
    ('Itoi Shigesato no Bass Tsuri No. 1', 5),
    ('J-League Dynamite Soccer 64', 5),
    ('J-League Eleven Beat 1997', 5),
    ('J. League Live 64', 5),
    ('J-League Tactics Soccer', 5),
    ('Jango Simulation Mahjong-do 64', 5),
    ('Jeopardy!', 5),
    ('Jeremy McGrath Supercross 2000', 5),
    ('Jet Force Gemini', 5),
    ('Jikkyo GI Stable', 5),
    ('Jikkyou World Soccer 3', 5),
    ('Jikkyo Powerful Pro Yakyu 4', 5),
    ('Jikkyo Powerful Pro Yakyu 5', 5),
    ('Jikkyo Powerful Pro Yakyu 6', 5),
    ('Jikkyo Powerful Pro Yakyu 2000', 5),
    ('Jikkyo Powerful Pro Yakyu Basic-ban 2001', 5),
    ('Jinsei Game 64', 5),
    ('Ken Griffey, Jr.''s Slugfest', 5),
    ('Killer Instinct Gold', 5),
    ('Kira tto Kaiketsu! 64 Tanteidan', 5),
    ('Kirby 64: The Crystal Shards', 5),
    ('Knife Edge: Nose Gunner•Knife EdgePAL', 5),
    ('Knockout Kings 2000•Box Champions 2000GER', 5),
    ('Kobe Bryant in NBA Courtside', 5),
    ('Last Legion UX', 5),
    ('The Legend of Zelda: Majora''s Mask', 5),
    ('The Legend of Zelda: Ocarina of Time', 5),
    ('LEGO Racers', 5),
    ('Lode Runner 3-D', 5),
    ('Mace: The Dark Age', 5),
    ('Madden Football 64', 5),
    ('Madden NFL 99', 5),
    ('Madden NFL 2000', 5),
    ('Madden NFL 2001', 5),
    ('Madden NFL 2002', 5),
    ('Magical Tetris Challenge', 5),
    ('Mahjong 64', 5),
    ('Mahjong Horoki Classic', 5),
    ('Mahjong Master', 5),
    ('Major League Baseball Featuring Ken Griffey, Jr.', 5),
    ('Mario Golf', 5),
    ('Mario Kart 64', 5),
    ('Mario no Photopi', 5),
    ('Mario Party', 5),
    ('Mario Party 2', 5),
    ('Mario Party 3', 5),
    ('Mario Tennis', 5),
    ('Masters ''98: Haruka Naru Augusta', 5),
    ('Mega Man 64', 5),
    ('Michael Owen''s WLS 2000•Mia Hamm 64 SoccerNA•RTL World League Soccer 2000GER•Telefoot Soccer 2000FRA', 5),
    ('Mickey''s Speedway USA', 5),
    ('Micro Machines 64 Turbo', 5),
    ('Midway''s Greatest Arcade Hits: Volume 1', 5),
    ('Mike Piazza''s Strike Zone', 5),
    ('Milo''s Astro Lanes', 5),
    ('Mischief Makers', 5),
    ('Mission: Impossible', 5),
    ('Monaco Grand Prix•Monaco Grand Prix: Racing Simulation 2PAL•Racing Simulation: Monaco Grand PrixUK•Racing Simulation 2GER', 5),
    ('Monopoly', 5),
    ('Monster Truck Madness 64', 5),
    ('Morita Shogi 64', 5),
    ('Mortal Kombat 4', 5),
    ('Mortal Kombat Mythologies: Sub-Zero', 5),
    ('Mortal Kombat Trilogy', 5),
    ('MRC: Multi-Racing Championship', 5),
    ('Ms. Pac-Man Maze Madness', 5),
    ('Mystical Ninja Starring Goemon', 5),
    ('Nagano Winter Olympics ''98', 5),
    ('Namco Museum 64', 5),
    ('NASCAR 99', 5),
    ('NASCAR 2000', 5),
    ('NBA Courtside 2: Featuring Kobe Bryant', 5),
    ('NBA Hangtime', 5),
    ('NBA In The Zone ''98•NBA Pro ''98PAL', 5),
    ('NBA In The Zone ''99•NBA Pro ''99PAL', 5),
    ('NBA In The Zone 2000', 5),
    ('NBA Jam ''99', 5),
    ('NBA Jam 2000', 5),
    ('NBA Live 99', 5),
    ('NBA Live 2000', 5),
    ('NBA Showtime: NBA on NBC', 5),
    ('Neon Genesis Evangelion', 5),
    ('New Japan Pro Wrestling: Tohkon Road Brave Spirits', 5),
    ('New Japan Pro Wrestling: Tohkon Road Brave Spirits 2, The Next Generation', 5),
    ('The New Tetris', 5),
    ('NFL Blitz', 5),
    ('NFL Blitz 2000', 5),
    ('NFL Blitz 2001', 5),
    ('NFL Blitz Special Edition', 5),
    ('NFL Quarterback Club ''98', 5),
    ('NFL Quarterback Club ''99', 5),
    ('NFL Quarterback Club 2000', 5),
    ('NFL QB Club 2001', 5),
    ('NHL 99', 5),
    ('NHL Blades of Steel ''99•NHL Pro ''99PAL', 5),
    ('NHL Breakaway ''98', 5),
    ('NHL Breakaway ''99', 5),
    ('Nightmare Creatures', 5),
    ('Nintama Rantaro 64 Game Gallery', 5),
    ('Nuclear Strike 64', 5),
    ('Nushi Tsuri 64', 5),
    ('Nushi Tsuri 64: Shiokaze ni Notte', 5),
    ('Off Road Challenge', 5),
    ('Ogre Battle 64: Person of Lordly Caliber', 5),
    ('Olympic Hockey Nagano ''98', 5),
    ('Onegai Monster', 5),
    ('Pachinko 365 Nichi', 5),
    ('Paper Mario', 5),
    ('Paperboy 64', 5),
    ('Parlor! Pro 64: Pachinko Jikki Simulation', 5),
    ('PD Ultraman Battle Collection 64', 5),
    ('Penny Racers', 5),
    ('Perfect Dark', 5),
    ('PGA European Tour•PGA European Tour Golf PAL', 5),
    ('Pilotwings 64', 5),
    ('Pocket Monsters Stadium', 5),
    ('Pokémon Puzzle League', 5),
    ('Pokémon Snap', 5),
    ('Pokémon Stadium', 5),
    ('Pokémon Stadium 2', 5),
    ('Polaris SnoCross', 5),
    ('Power League 64', 5),
    ('Power Rangers Lightspeed Rescue', 5),
    ('The Powerpuff Girls: Chemical X-traction', 5),
    ('Premier Manager 64', 5),
    ('Pro Mahjong Kiwame 64', 5),
    ('Pro Shinan Mahjong Tsuwamono 64: Janso Battle ni Chosen', 5),
    ('Puyo Puyo Sun 64', 5),
    ('Puyo Puyo~n Party', 5),
    ('Quake 64', 5),
    ('Quake II', 5),
    ('Quest 64•Holy Magic CenturyPAL', 5),
    ('Rainbow Six', 5),
    ('Rakugakids', 5),
    ('Rally Challenge 2000', 5),
    ('Rampage 2: Universal Tour', 5),
    ('Rampage World Tour', 5),
    ('Rat Attack!', 5),
    ('Rayman 2: The Great Escape', 5),
    ('Razor Freestyle Scooter', 5),
    ('Re-Volt', 5),
    ('Ready 2 Rumble Boxing', 5),
    ('Ready 2 Rumble Boxing: Round 2', 5),
    ('Resident Evil 2', 5),
    ('Ridge Racer 64', 5),
    ('Road Rash 64', 5),
    ('Roadsters', 5),
    ('Robot Ponkottsu 64: Nanatsu no Umi no Caramel', 5),
    ('Robotron 64', 5),
    ('Rocket: Robot on Wheels', 5),
    ('Rugrats in Paris: The Movie', 5),
    ('Rugrats: Scavenger Hunt•Rugrats: Treasure HuntPAL', 5),
    ('Rush 2: Extreme Racing USA', 5),
    ('S.C.A.R.S.', 5),
    ('Saikyō Habu Shōgi', 5),
    ('San Francisco Rush: Extreme Racing', 5),
    ('San Francisco Rush 2049', 5),
    ('Scooby-Doo! Classic Creep Capers', 5),
    ('SD Hiryu no Ken Densetsu', 5),
    ('Shadow Man', 5),
    ('Shadowgate 64: Trials of the Four Towers', 5),
    ('Shiren the Wanderer 2', 5),
    ('SimCity 2000', 5),
    ('Sin and Punishment', 5),
    ('Snowboard Kids', 5),
    ('Snowboard Kids 2', 5),
    ('South Park', 5),
    ('South Park Rally', 5),
    ('South Park: Chef''s Luv Shack', 5),
    ('Space Invaders', 5),
    ('Space Station Silicon Valley', 5),
    ('Spider-Man', 5),
    ('Star Fox 64•Lylat Wars PAL', 5),
    ('Star Soldier: Vanishing Earth', 5),
    ('Star Wars: Episode I: Battle for Naboo', 5),
    ('Star Wars Episode I: Racer', 5),
    ('Star Wars: Rogue Squadron', 5),
    ('Star Wars: Shadows of the Empire', 5),
    ('StarCraft 64', 5),
    ('Starshot: Space Circus Fever', 5),
    ('Stunt Racer 64', 5),
    ('Super B-Daman: Battle Phoenix 64', 5),
    ('Super Bowling', 5),
    ('Super Mario 64', 5),
    ('Super Robot Spirits', 5),
    ('Super Robot Wars 64', 5),
    ('Super Smash Bros.', 5),
    ('Supercross 2000', 5),
    ('Superman 64', 5),
    ('Susume! Taisen Puzzle Dama: Tokon! Marutama Cho', 5),
    ('Tamagotchi 64: Minna de Tamagotchi World', 5),
    ('Taz Express', 5),
    ('Tetris 64', 5),
    ('Tetrisphere', 5),
    ('Tigger''s Honey Hunt', 5),
    ('Tom and Jerry in Fists of Furry', 5),
    ('Tonic Trouble', 5),
    ('Tony Hawk''s Pro Skater•Tony Hawk''s SkateboardingPAL', 5),
    ('Tony Hawk''s Pro Skater 2', 5),
    ('Tony Hawk''s Pro Skater 3', 5),
    ('Top Gear Hyper Bike', 5),
    ('Top Gear Overdrive', 5),
    ('Top Gear Rally', 5),
    ('Top Gear Rally 2', 5),
    ('Toy Story 2: Buzz Lightyear to the Rescue', 5),
    ('Transformers: Beast Wars Transmetals', 5),
    ('Triple Play 2000', 5),
    ('Turok: Dinosaur Hunter', 5),
    ('Turok 2: Seeds of Evil', 5),
    ('Turok 3: Shadow of Oblivion', 5),
    ('Turok: Rage Wars', 5),
    ('Twisted Edge Extreme Snowboarding', 5),
    ('Ucchan Nanchan no Hono no Challenge: Denryu Ira Ira Bo', 5),
    ('V-Rally Edition ''99', 5),
    ('Vigilante 8', 5),
    ('Vigilante 8: 2nd Offense', 5),
    ('Virtual Chess 64', 5),
    ('Virtual Pool 64', 5),
    ('Virtual Pro Wrestling 2: Odo Keisho', 5),
    ('Virtual Pro Wrestling 64', 5),
    ('Waialae Country Club: True Golf Classics', 5),
    ('War Gods', 5),
    ('Wave Race 64', 5),
    ('Wayne Gretzky''s 3D Hockey', 5),
    ('Wayne Gretzky''s 3D Hockey ''98', 5),
    ('WCW Backstage Assault', 5),
    ('WCW Mayhem', 5),
    ('WCW Nitro', 5),
    ('WCW vs. nWo: World Tour', 5),
    ('WCW/nWo Revenge', 5),
    ('Wetrix', 5),
    ('Wheel of Fortune', 5),
    ('WinBack•Operation: WinbackPAL', 5),
    ('Wipeout 64', 5),
    ('Wonder Project J2: Corlo no Mori no Josette', 5),
    ('World Cup 98', 5),
    ('World Driver Championship', 5),
    ('The World Is Not Enough', 5),
    ('Worms Armageddon', 5),
    ('WWF Attitude', 5),
    ('WWF No Mercy', 5),
    ('WWF War Zone', 5),
    ('WWF WrestleMania 2000', 5),
    ('Xena: Warrior Princess: The Talisman of Fate•Xena: Warrior PrincessPAL', 5),
    ('Yakochu II: Satsujin Koro', 5),
    ('Yoshi''s Story', 5),
    ('Zoor: Maju Tsukai Densetsu', 5);

INSERT INTO "game" (name, platform_id) VALUES
    ('1080° Snowboarding', 5),
    ('64 Hanafuda: Tenshi no Yakusoku', 5),
    ('64 Ozumo', 5),
    ('64 Ozumo 2', 5),
    ('64 Trump Collection: Alice no Waku Waku Trump World', 5),
    ('Aero Fighters Assault', 5),
    ('AeroGauge', 5),
    ('AI Shogi 3', 5),
    ('Aidyn Chronicles: The First Mage', 5),
    ('Air Boarder 64', 5),
    ('All-Star Baseball 99', 5),
    ('All-Star Baseball 2000', 5),
    ('All-Star Baseball 2001', 5),
    ('All Star Tennis ''99•Yannick Noah All Star Tennis ''99FRA', 5),
    ('Armorines: Project S.W.A.R.M.', 5),
    ('Army Men: Air Combat', 5),
    ('Army Men: Sarge''s Heroes', 5),
    ('Army Men: Sarge''s Heroes 2', 5),
    ('Asteroids Hyper 64', 5),
    ('Automobili Lamborghini', 5),
    ('Bakuretsu Muteki Bangai-O', 5),
    ('Bakusho Jinsei 64: Mezase! Resort O', 5),
    ('Banjo-Kazooie', 5),
    ('Banjo-Tooie', 5),
    ('Bass Hunter 64', 5),
    ('Bass Masters 2000', 5),
    ('Bass Rush: ECOGEAR PowerWorm Championship', 5),
    ('Batman Beyond: Return of the Joker•Batman of the Future: Return of the JokerPAL', 5),
    ('BattleTanx', 5),
    ('BattleTanx: Global Assault', 5),
    ('Battlezone: Rise of the Black Dogs', 5),
    ('Beetle Adventure Racing!•HSV Adventure RacingAUS', 5),
    ('Big Mountain 2000', 5),
    ('Bio F.R.E.A.K.S.', 5),
    ('Blast Corps', 5),
    ('Blues Brothers 2000', 5),
    ('Body Harvest', 5),
    ('Bomberman 64', 5),
    ('Bomberman 64', 5),
    ('Bomberman 64: The Second Attack', 5),
    ('Bomberman Hero', 5),
    ('Bottom of the 9th', 5),
    ('Brunswick Circuit Pro Bowling', 5),
    ('Buck Bumble', 5),
    ('A Bug''s Life', 5),
    ('Bust-A-Move ''99•Bust-A-Move 3 DXPAL', 5),
    ('Bust-A-Move 2: Arcade Edition', 5),
    ('California Speed', 5),
    ('Carmageddon 64', 5),
    ('Castlevania', 5),
    ('Castlevania: Legacy of Darkness', 5),
    ('Centre Court Tennis', 5),
    ('Chameleon Twist', 5),
    ('Chameleon Twist 2', 5),
    ('Charlie Blast''s Territory', 5),
    ('Chopper Attack', 5),
    ('Choro Q 64 2: Hachamecha Grand Prix Race', 5),
    ('Chokukan Night: Pro Yakyu King', 5),
    ('Chokukan Night: Pro Yakyu King 2', 5),
    ('ClayFighter 63⅓', 5),
    ('ClayFighter Sculptor''s Cut', 5),
    ('Command & Conquer', 5),
    ('Conker''s Bad Fur Day', 5),
    ('Cruis''n Exotica', 5),
    ('Cruis''n USA', 5),
    ('Cruis''n World', 5),
    ('Custom Robo', 5),
    ('Custom Robo V2', 5),
    ('CyberTiger', 5),
    ('Daikatana', 5),
    ('Dance Dance Revolution Disney Dancing Museum', 5),
    ('Dark Rift', 5),
    ('Densha de Go! 64', 5),
    ('Derby Stallion 64', 5),
    ('Destruction Derby 64', 5),
    ('Dezaemon 3D', 5),
    ('Diddy Kong Racing', 5),
    ('Donald Duck: Goin'' Quackers•Donald Duck''s Quack AttackPAL', 5),
    ('Disney''s Tarzan', 5),
    ('Donkey Kong 64', 5),
    ('Doom 64', 5),
    ('Doraemon: Nobita to Mittsu no Seireiseki', 5),
    ('Doraemon 2: Nobita to Hikari no Shinden', 5),
    ('Doraemon 3: Nobita no Machi SOS!', 5),
    ('Dobutsu no Mori', 5),
    ('Dr. Mario 64', 5),
    ('Dual Heroes', 5),
    ('Duck Dodgers Starring Daffy Duck•Daffy Duck starring as Duck DodgersPAL', 5),
    ('Duke Nukem 64', 5),
    ('Duke Nukem: Zero Hour', 5),
    ('Earthworm Jim 3D', 5),
    ('ECW Hardcore Revolution', 5),
    ('Eiko no Saint Andrews', 5),
    ('Elmo''s Letter Adventure', 5),
    ('Elmo''s Number Journey', 5),
    ('Excitebike 64', 5),
    ('Extreme-G', 5),
    ('Extreme-G 2', 5),
    ('F-1 World Grand Prix', 5),
    ('F-1 World Grand Prix II', 5),
    ('F-Zero X', 5),
    ('F1 Pole Position 64', 5),
    ('F1 Racing Championship', 5),
    ('Famista 64', 5),
    ('FIFA ''99', 5),
    ('FIFA: Road to World Cup 98', 5),
    ('FIFA Soccer 64•FIFA 64PAL', 5),
    ('Fighters Destiny', 5),
    ('Fighter Destiny 2', 5),
    ('Fighting Force 64', 5),
    ('Flying Dragon', 5),
    ('Forsaken 64•ForsakenPAL', 5),
    ('Fox Sports College Hoops ''99', 5),
    ('G.A.S.P!! Fighters'' NEXTream•Deadly ArtsNA', 5),
    ('Gauntlet Legends', 5),
    ('Getter Love!!', 5),
    ('Gex 3: Deep Cover Gecko', 5),
    ('Gex 64: Enter the Gecko', 5),
    ('Glover', 5),
    ('Goemon Mononoke Sugoroku', 5),
    ('Goemon''s Great Adventure•Mystical Ninja 2: Starring GoemonPAL', 5),
    ('Golden Nugget 64', 5),
    ('GoldenEye 007', 5),
    ('GT 64: Championship Edition', 5),
    ('Hamster Monogatari 64', 5),
    ('Harvest Moon 64', 5),
    ('Heiwa Pachinko World 64', 5),
    ('Hercules: The Legendary Journeys', 5),
    ('Hexen', 5),
    ('Hey You, Pikachu!', 5),
    ('Hot Wheels Turbo Racing', 5),
    ('Hybrid Heaven', 5),
    ('Hydro Thunder', 5),
    ('Ide Yosuke no Mahjong Juku', 5),
    ('Iggy''s Reckin'' Balls', 5),
    ('Indiana Jones and the Infernal Machine', 5),
    ('Indy Racing 2000', 5),
    ('International Superstar Soccer ''98', 5),
    ('International Superstar Soccer 2000', 5),
    ('International Superstar Soccer 64', 5),
    ('International Track & Field 2000•International Track & Field: Summer GamesPAL', 5),
    ('Itoi Shigesato no Bass Tsuri No. 1', 5),
    ('J-League Dynamite Soccer 64', 5),
    ('J-League Eleven Beat 1997', 5),
    ('J. League Live 64', 5),
    ('J-League Tactics Soccer', 5),
    ('Jango Simulation Mahjong-do 64', 5),
    ('Jeopardy!', 5),
    ('Jeremy McGrath Supercross 2000', 5),
    ('Jet Force Gemini', 5),
    ('Jikkyo GI Stable', 5),
    ('Jikkyou World Soccer 3', 5),
    ('Jikkyo Powerful Pro Yakyu 4', 5),
    ('Jikkyo Powerful Pro Yakyu 5', 5),
    ('Jikkyo Powerful Pro Yakyu 6', 5),
    ('Jikkyo Powerful Pro Yakyu 2000', 5),
    ('Jikkyo Powerful Pro Yakyu Basic-ban 2001', 5),
    ('Jinsei Game 64', 5),
    ('Ken Griffey, Jr.''s Slugfest', 5),
    ('Killer Instinct Gold', 5),
    ('Kira tto Kaiketsu! 64 Tanteidan', 5),
    ('Kirby 64: The Crystal Shards', 5),
    ('Knife Edge: Nose Gunner•Knife EdgePAL', 5),
    ('Knockout Kings 2000•Box Champions 2000GER', 5),
    ('Kobe Bryant in NBA Courtside', 5),
    ('Last Legion UX', 5),
    ('The Legend of Zelda: Majora''s Mask', 5),
    ('The Legend of Zelda: Ocarina of Time', 5),
    ('LEGO Racers', 5),
    ('Lode Runner 3-D', 5),
    ('Mace: The Dark Age', 5),
    ('Madden Football 64', 5),
    ('Madden NFL 99', 5),
    ('Madden NFL 2000', 5),
    ('Madden NFL 2001', 5),
    ('Madden NFL 2002', 5),
    ('Magical Tetris Challenge', 5),
    ('Mahjong 64', 5),
    ('Mahjong Horoki Classic', 5),
    ('Mahjong Master', 5),
    ('Major League Baseball Featuring Ken Griffey, Jr.', 5),
    ('Mario Golf', 5),
    ('Mario Kart 64', 5),
    ('Mario no Photopi', 5),
    ('Mario Party', 5),
    ('Mario Party 2', 5),
    ('Mario Party 3', 5),
    ('Mario Tennis', 5),
    ('Masters ''98: Haruka Naru Augusta', 5),
    ('Mega Man 64', 5),
    ('Michael Owen''s WLS 2000•Mia Hamm 64 SoccerNA•RTL World League Soccer 2000GER•Telefoot Soccer 2000FRA', 5),
    ('Mickey''s Speedway USA', 5),
    ('Micro Machines 64 Turbo', 5),
    ('Midway''s Greatest Arcade Hits: Volume 1', 5),
    ('Mike Piazza''s Strike Zone', 5),
    ('Milo''s Astro Lanes', 5),
    ('Mischief Makers', 5),
    ('Mission: Impossible', 5),
    ('Monaco Grand Prix•Monaco Grand Prix: Racing Simulation 2PAL•Racing Simulation: Monaco Grand PrixUK•Racing Simulation 2GER', 5),
    ('Monopoly', 5),
    ('Monster Truck Madness 64', 5),
    ('Morita Shogi 64', 5),
    ('Mortal Kombat 4', 5),
    ('Mortal Kombat Mythologies: Sub-Zero', 5),
    ('Mortal Kombat Trilogy', 5),
    ('MRC: Multi-Racing Championship', 5),
    ('Ms. Pac-Man Maze Madness', 5),
    ('Mystical Ninja Starring Goemon', 5),
    ('Nagano Winter Olympics ''98', 5),
    ('Namco Museum 64', 5),
    ('NASCAR 99', 5),
    ('NASCAR 2000', 5),
    ('NBA Courtside 2: Featuring Kobe Bryant', 5),
    ('NBA Hangtime', 5),
    ('NBA In The Zone ''98•NBA Pro ''98PAL', 5),
    ('NBA In The Zone ''99•NBA Pro ''99PAL', 5),
    ('NBA In The Zone 2000', 5),
    ('NBA Jam ''99', 5),
    ('NBA Jam 2000', 5),
    ('NBA Live 99', 5),
    ('NBA Live 2000', 5),
    ('NBA Showtime: NBA on NBC', 5),
    ('Neon Genesis Evangelion', 5),
    ('New Japan Pro Wrestling: Tohkon Road Brave Spirits', 5),
    ('New Japan Pro Wrestling: Tohkon Road Brave Spirits 2, The Next Generation', 5),
    ('The New Tetris', 5),
    ('NFL Blitz', 5),
    ('NFL Blitz 2000', 5),
    ('NFL Blitz 2001', 5),
    ('NFL Blitz Special Edition', 5),
    ('NFL Quarterback Club ''98', 5),
    ('NFL Quarterback Club ''99', 5),
    ('NFL Quarterback Club 2000', 5),
    ('NFL QB Club 2001', 5),
    ('NHL 99', 5),
    ('NHL Blades of Steel ''99•NHL Pro ''99PAL', 5),
    ('NHL Breakaway ''98', 5),
    ('NHL Breakaway ''99', 5),
    ('Nightmare Creatures', 5),
    ('Nintama Rantaro 64 Game Gallery', 5),
    ('Nuclear Strike 64', 5),
    ('Nushi Tsuri 64', 5),
    ('Nushi Tsuri 64: Shiokaze ni Notte', 5),
    ('Off Road Challenge', 5),
    ('Ogre Battle 64: Person of Lordly Caliber', 5),
    ('Olympic Hockey Nagano ''98', 5),
    ('Onegai Monster', 5),
    ('Pachinko 365 Nichi', 5),
    ('Paper Mario', 5),
    ('Paperboy 64', 5),
    ('Parlor! Pro 64: Pachinko Jikki Simulation', 5),
    ('PD Ultraman Battle Collection 64', 5),
    ('Penny Racers', 5),
    ('Perfect Dark', 5),
    ('PGA European Tour•PGA European Tour Golf PAL', 5),
    ('Pilotwings 64', 5),
    ('Pocket Monsters Stadium', 5),
    ('Pokémon Puzzle League', 5),
    ('Pokémon Snap', 5),
    ('Pokémon Stadium', 5),
    ('Pokémon Stadium 2', 5),
    ('Polaris SnoCross', 5),
    ('Power League 64', 5),
    ('Power Rangers Lightspeed Rescue', 5),
    ('The Powerpuff Girls: Chemical X-traction', 5),
    ('Premier Manager 64', 5),
    ('Pro Mahjong Kiwame 64', 5),
    ('Pro Shinan Mahjong Tsuwamono 64: Janso Battle ni Chosen', 5),
    ('Puyo Puyo Sun 64', 5),
    ('Puyo Puyo~n Party', 5),
    ('Quake 64', 5),
    ('Quake II', 5),
    ('Quest 64•Holy Magic CenturyPAL', 5),
    ('Rainbow Six', 5),
    ('Rakugakids', 5),
    ('Rally Challenge 2000', 5),
    ('Rampage 2: Universal Tour', 5),
    ('Rampage World Tour', 5),
    ('Rat Attack!', 5),
    ('Rayman 2: The Great Escape', 5),
    ('Razor Freestyle Scooter', 5),
    ('Re-Volt', 5),
    ('Ready 2 Rumble Boxing', 5),
    ('Ready 2 Rumble Boxing: Round 2', 5),
    ('Resident Evil 2', 5),
    ('Ridge Racer 64', 5),
    ('Road Rash 64', 5),
    ('Roadsters', 5),
    ('Robot Ponkottsu 64: Nanatsu no Umi no Caramel', 5),
    ('Robotron 64', 5),
    ('Rocket: Robot on Wheels', 5),
    ('Rugrats in Paris: The Movie', 5),
    ('Rugrats: Scavenger Hunt•Rugrats: Treasure HuntPAL', 5),
    ('Rush 2: Extreme Racing USA', 5),
    ('S.C.A.R.S.', 5),
    ('Saikyō Habu Shōgi', 5),
    ('San Francisco Rush: Extreme Racing', 5),
    ('San Francisco Rush 2049', 5),
    ('Scooby-Doo! Classic Creep Capers', 5),
    ('SD Hiryu no Ken Densetsu', 5),
    ('Shadow Man', 5),
    ('Shadowgate 64: Trials of the Four Towers', 5),
    ('Shiren the Wanderer 2', 5),
    ('SimCity 2000', 5),
    ('Sin and Punishment', 5),
    ('Snowboard Kids', 5),
    ('Snowboard Kids 2', 5),
    ('South Park', 5),
    ('South Park Rally', 5),
    ('South Park: Chef''s Luv Shack', 5),
    ('Space Invaders', 5),
    ('Space Station Silicon Valley', 5),
    ('Spider-Man', 5),
    ('Star Fox 64•Lylat Wars PAL', 5),
    ('Star Soldier: Vanishing Earth', 5),
    ('Star Wars: Episode I: Battle for Naboo', 5),
    ('Star Wars Episode I: Racer', 5),
    ('Star Wars: Rogue Squadron', 5),
    ('Star Wars: Shadows of the Empire', 5),
    ('StarCraft 64', 5),
    ('Starshot: Space Circus Fever', 5),
    ('Stunt Racer 64', 5),
    ('Super B-Daman: Battle Phoenix 64', 5),
    ('Super Bowling', 5),
    ('Super Mario 64', 5),
    ('Super Robot Spirits', 5),
    ('Super Robot Wars 64', 5),
    ('Super Smash Bros.', 5),
    ('Supercross 2000', 5),
    ('Superman 64', 5),
    ('Susume! Taisen Puzzle Dama: Tokon! Marutama Cho', 5),
    ('Tamagotchi 64: Minna de Tamagotchi World', 5),
    ('Taz Express', 5),
    ('Tetris 64', 5),
    ('Tetrisphere', 5),
    ('Tigger''s Honey Hunt', 5),
    ('Tom and Jerry in Fists of Furry', 5),
    ('Tonic Trouble', 5),
    ('Tony Hawk''s Pro Skater•Tony Hawk''s SkateboardingPAL', 5),
    ('Tony Hawk''s Pro Skater 2', 5),
    ('Tony Hawk''s Pro Skater 3', 5),
    ('Top Gear Hyper Bike', 5),
    ('Top Gear Overdrive', 5),
    ('Top Gear Rally', 5),
    ('Top Gear Rally 2', 5),
    ('Toy Story 2: Buzz Lightyear to the Rescue', 5),
    ('Transformers: Beast Wars Transmetals', 5),
    ('Triple Play 2000', 5),
    ('Turok: Dinosaur Hunter', 5),
    ('Turok 2: Seeds of Evil', 5),
    ('Turok 3: Shadow of Oblivion', 5),
    ('Turok: Rage Wars', 5),
    ('Twisted Edge Extreme Snowboarding', 5),
    ('Ucchan Nanchan no Hono no Challenge: Denryu Ira Ira Bo', 5),
    ('V-Rally Edition ''99', 5),
    ('Vigilante 8', 5),
    ('Vigilante 8: 2nd Offense', 5),
    ('Virtual Chess 64', 5),
    ('Virtual Pool 64', 5),
    ('Virtual Pro Wrestling 2: Odo Keisho', 5),
    ('Virtual Pro Wrestling 64', 5),
    ('Waialae Country Club: True Golf Classics', 5),
    ('War Gods', 5),
    ('Wave Race 64', 5),
    ('Wayne Gretzky''s 3D Hockey', 5),
    ('Wayne Gretzky''s 3D Hockey ''98', 5),
    ('WCW Backstage Assault', 5),
    ('WCW Mayhem', 5),
    ('WCW Nitro', 5),
    ('WCW vs. nWo: World Tour', 5),
    ('WCW/nWo Revenge', 5),
    ('Wetrix', 5),
    ('Wheel of Fortune', 5),
    ('WinBack•Operation: WinbackPAL', 5),
    ('Wipeout 64', 5),
    ('Wonder Project J2: Corlo no Mori no Josette', 5),
    ('World Cup 98', 5),
    ('World Driver Championship', 5),
    ('The World Is Not Enough', 5),
    ('Worms Armageddon', 5),
    ('WWF Attitude', 5),
    ('WWF No Mercy', 5),
    ('WWF War Zone', 5),
    ('WWF WrestleMania 2000', 5),
    ('Xena: Warrior Princess: The Talisman of Fate•Xena: Warrior PrincessPAL', 5),
    ('Yakochu II: Satsujin Koro', 5),
    ('Yoshi''s Story', 5),
    ('Zoor: Maju Tsukai Densetsu', 5);
